name: Yardoc

# check documentation in specified paths
on: # `on` parses to `true` in ruby
  pull_request:
    paths:
      # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
      - modules/burials/**/*.rb
      
permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  yardoc:
    name: Yardoc

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Yardoc
        run: git log --oneline